django_project/app_3ingredients/urls.py
from django.urls import path

from . import views

app_name = "app_3ingredients"

urlpatterns = [
    path("", views.EnterIngredientsView.as_view(), name='index'),
    path("results", views.ResultsView.as_view(), name="results"),
    path("results/rate/", views.recipe_rating, name="rate")
]

django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("", include("app_3ingredients.urls")),
    path("admin/", admin.site.urls),
]

django_project/app_3ingredients/models.py
from django.db import models


class Recipe(models.Model):
    title = models.TextField()
    ingredients = models.TextField()
    description = models.TextField()
    cooking_time = models.IntegerField()
    servings = models.IntegerField()
    url = models.TextField()
    rating = models.IntegerField()
    category = models.IntegerField(null=True)


django_project/fridge_cleaner/models.py
from django.db import models


class Recipes(models.Model):
    title = models.TextField()
    ingredients = models.TextField()
    description = models.TextField()
    cooking_time = models.IntegerField()
    servings = models.IntegerField()
    url = models.TextField()
    rating = models.IntegerField()
    group = models.IntegerField()


django_project/app_3ingredients/forms.py
from django import forms


class EnterIngredientsForm(forms.Form):
    ingredient_1 = forms.CharField(required=False)
    ingredient_2 = forms.CharField(required=False)
    ingredient_3 = forms.CharField(required=False)

django_project/app_3ingredients/views.py
from django.views.generic import FormView
from django.views.generic import ListView
from django.shortcuts import redirect
from django.core import serializers
from django.http import JsonResponse
import json

from .forms import EnterIngredientsForm
from .models import Recipe


class EnterIngredientsView(FormView):
    form_class = EnterIngredientsForm
    template_name = "form_view.html"
    success_url = "results"

    def post(self, request, *args, **kwargs):
        request.session["ingredients"] = [
            request.POST["ingredient_1"],
            request.POST["ingredient_2"],
            request.POST["ingredient_3"]
        ]
        request.session["results"] = None
        return super(EnterIngredientsView, self).post(request, *args, **kwargs)


class ResultsView(ListView):
    template_name = "list_view.html"
    context_object_name = "recipes"
    request = None
    extra_context = None
    paginate_by = 5

    def get(self, request, *args, **kwargs):
        self.extra_context = {"ingredients": request.session.get("ingredients")}
        self.request = request
        return super(ResultsView, self).get(request, *args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        if not self.request.session.get("results"):
            queryset = self.search_recipes()
            serialized_queryset = json.loads(serializers.serialize("json", queryset))
            json_context = (self.create_json_context(serialized_queryset))
            self.request.session["results"] = json_context
            return json_context
        else:
            for result in self.request.session.get("results"):
                recipe = Recipe.objects.get(pk=result["id"])
                result["rating"] = recipe.rating
            return self.request.session.get("results")

    def search_recipes(self):
        top_rated = self.filter_by_ingredients().order_by("-rating")
        category_1 = self.filter_by_ingredients().filter(category=1).order_by("?")
        category_2 = self.filter_by_ingredients().filter(category=2).order_by("?")
        category_3 = self.filter_by_ingredients().filter(category=3).order_by("?")

        results = []
        current_ids = []
        top_rated_count = len(top_rated)
        category_1_count = len(category_1)
        category_2_count = len(category_2)
        category_3_count = len(category_3)

        for iteration in range(top_rated_count):
            if top_rated[iteration].pk not in current_ids:
                current_ids.append(top_rated[iteration].pk)
                results.append(top_rated[iteration])
            if iteration < category_1_count:
                if category_1[iteration].pk not in current_ids:
                    current_ids.append(category_1[iteration].pk)
                    results.append(category_1[iteration])
            if iteration < category_2_count:
                if category_2[iteration].pk not in current_ids:
                    current_ids.append(category_2[iteration].pk)
                    results.append(category_2[iteration])
            if iteration < category_3_count:
                if category_3[iteration].pk not in current_ids:
                    current_ids.append(category_3[iteration].pk)
                    results.append(category_3[iteration])
        return results

    def filter_by_ingredients(self):
        return Recipe.objects.filter(
            ingredients__icontains=self.extra_context["ingredients"][0]
        ).filter(
            ingredients__icontains=self.extra_context["ingredients"][1]
        ).filter(
            ingredients__icontains=self.extra_context["ingredients"][2]
        )

    def create_json_context(self, serialized_queryset):
        json_context = []
        for recipe in serialized_queryset:
            ingredients = json.loads(recipe["fields"]["ingredients"])
            description = json.loads(recipe["fields"]["description"])
            cooking_time = f'{int(recipe["fields"]["cooking_time"]/60)}:{(recipe["fields"]["cooking_time"]%60):02d} h'
            json_context.append({
                "id": recipe["pk"],
                "title": recipe["fields"]["title"],
                "ingredients": ingredients,
                "description": description,
                "cooking_time": cooking_time,
                "servings": recipe["fields"]["servings"],
                "url": recipe["fields"]["url"],
                "rating": recipe["fields"]["rating"]
            })
        return json_context


def recipe_rating(request):
    if request.method == "POST":
        recipe_id = request.POST.get("recipe_id")
        value = request.POST.get("value")
        recipe_obj = Recipe.objects.get(id=recipe_id)
        rating = recipe_obj.rating
        if value == "Unlike" and rating > 0:
            rating -= 1
        elif value == "Looks delicious!":
            rating += 1
        recipe_obj.rating = rating
        recipe_obj.save()
        data = {
            "value": value,
            "rating": rating
        }
        response = JsonResponse(data, safe=False)
        if value == "Looks delicious!":
            response.set_cookie(f"rated_{recipe_id}", value, max_age=60*60*24*365*2, samesite="Lax")
        return response
    return redirect("app_3ingredients:results")

django_project/templates/form_view.html
{% extends "root.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static "css/form.css" %}">
<div class="container text-center">
    <div class="row mb-5">
        <div class="col" style="margin-bottom: 250px;">
            <img id="logo" src="{% static "images/logo.png" %}" alt="3 ingredients"/>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-4 offset-4 instructions">
            Enter up to three ingredients:
        </div>
    </div>
    <div class="row mt-4">
        <div class="col">
            <form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                <div style="padding: 1px;">{{ form.ingredient_1 }}</div>
                <div style="padding: 1px;">{{ form.ingredient_2 }}</div>
                <div style="padding: 1px;">{{ form.ingredient_3 }}</div>
                <div style="padding: 2px; text-align: center;">
                    <button class="my-3 px-3 py-1 search-button" type="submit">Let's go</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

django_project/templates/head.html
<head>

	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

	<title>3 ingredients</title>

    {% load static %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />

    <style>
        #bg {
            background-image: url("{% static 'images/background.jpg' %}");
            background-repeat: no-repeat;
            background-position: top;
            background-attachment: fixed;
            background-size: 100% 100%;
        }
        #logo {
            position: fixed;
            top: 10px;
            right: 100px;
        }
    </style>
</head>

django_project/templates/list_view.html
{% extends "root.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static "css/list.css" %}">

<div class="container text-center">
    <a href="/"><img id="logo" src="{% static "images/logo.png" %}" alt="3 ingredients"/></a>
    <div id="ingredients" style="background-image: url('{% static "images/ingredients_bg.png" %}');">
        <div id="ingredients_list">
            <h4 class="mt-5">Ingredients:</h4>
            {% for ingredient in ingredients %}
                <div class="my-1 font-weight-bold">{{ ingredient }}</div>
            {% endfor %}
        </div>
    </div>
    <div id="results" class="col-lg-8 offset-lg-2 mt-3">
        <h5 id="results_header" class="p-2">Results:</h5>
        {% for recipe in recipes %}
            <div>
                <a href="#recipe-{{ recipe.id }}" data-toggle="collapse" aria-expanded="false" class="dropdown" style="background-image: url('{% static "images/result_bg.png" %}');">{{ recipe.title }}</a>
                <div class="collapse mb-3 scroll-top" id="recipe-{{ recipe.id }}">
                    <div class="container result" style="background-image: url('{% static "images/recipe_bg.png" %}');">
                        <div class="row">
                            <div class="col mt-3"><h3>{{ recipe.title }}</h3></div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <h5>Cooking time:</h5>
                                {{ recipe.cooking_time }}
                                <h5 class="mt-2">Servings:</h5>
                                {{ recipe.servings }}
                                <h5 class="mt-2">Ingredients:</h5>
                                <ul>
                                    {% for ingredient in recipe.ingredients %}
                                    <li>{{ ingredient }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="col-md-8">
                                <h5>Recipe:</h5>
                                <ul>
                                    {% for step in recipe.description %}
                                    <li>{{ step }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <form id="{{ recipe.id }}" action="{% url 'app_3ingredients:rate' %}" method="POST" class="rating-form p-2">
                                    {% csrf_token %}
                                    <input type="hidden" name="recipe_id" value="{{ recipe.id }}">
                                    <button id="rate-{{ recipe.id }}" class="btn" type="submit">Looks delicious!</button>
                                </form>
                                <div style="display: inline-block">Liked it: </div>
                                <div id="rating-{{ recipe.id }}" style="display: inline-block">{{ recipe.rating }}</div>
                                <a style="display: block; padding: 5px;" href="{{ recipe.url }}" target="_blank">See original recipe</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="bg-light my-4 p-3"><h4>No recipes found for your ingredients :(</h4></div>
        {% endfor %}
    </div>
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-dark my-4 page-button" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% else %}
            <a class="btn btn-outline-dark my-4 page-button-inactive">Previous</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a id="current_page" class="btn my-4 font-weight-bold" style="background-color: #ca8017" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a class="btn btn-outline-dark my-4 page-button" href="?page={{ page_obj.next_page_number }}">Next</a>
        {% else %}
            <a class="btn btn-outline-dark my-4 page-button-inactive">Next</a>
        {% endif %}
    {% endif %}
</div>

<script src="{% static "js/scroll_top.js" %}"></script>
<script src="{% static "js/recipe_cookies.js" %}"></script>
<script src="{% static "js/recipe_rating.js" %}"></script>

{% endblock %}

django_project/templates/root.html
<!DOCTYPE html>
<html lang="en">

{% include "head.html" %}
<body id="bg">
    {% include "overlay.html" %}
    {% block content %}
    {% endblock %}
    {% include "footer.html" %}
</body>
</html>